My Receipts Page
LideLinusZhang/cs446-project pull request #53
Opened 2024-07-19 07:30 UTC by SamuelLiSiyuan

My Receipts Page UI and logic
![myReceiptsPage](https://github.com/user-attachments/assets/26f2c21e-f4b0-47f6-b696-701b45a907ce)

2024-07-19 07:40 UTC, SamuelLiSiyuan commented
What should be on the View Receipt Page?

2024-07-19 19:06 UTC, NandiniMeh reviewed
On the View Receipt page, it should just be the receipt itself, and the information related to it (like date, purchase type, amount, card used etc) not sure if anyone else is working on this though @rachellefontanilla @sophiec103 @jeanniezhang

This is regarding the button for "view" right

2024-07-20 05:56 UTC, SamuelLiSiyuan commented
> date, purchase type, amount, card used

Since all this information is already shown on this page, if no more detailed information needs to be presented, I am not sure if it is necessary to have a separate page for it. 

Anyway, if no one is working on the view receipt page, I can take it.

2024-07-20 06:39 UTC, NandiniMeh commented
> > date, purchase type, amount, card used
> 
> Since all this information is already shown on this page, if no more detailed information needs to be presented, I am not sure if it is necessary to have a separate page for it.
> 
> Anyway, if no one is working on the view receipt page, I can take it.

hmmm thats a good point. maybe a way to see the image would be good? any suggestions would be great. like for example, if there's a way to get the image of the receipt to be saved to gallery or something

2024-07-23 14:12 UTC, LideLinusZhang requested changes

2024-07-23 14:12 UTC, LideLinusZhang commented on app/src/main/java/edu/card/clarity/domain/creditCard/CreditCardInfo.kt
Don't pollute the domain model with ui state stuff such as `@Parcelize`.

2024-07-24 01:30 UTC, LideLinusZhang approved these changes

2024-07-24 01:30 UTC, LideLinusZhang commented on app/src/main/java/edu/card/clarity/presentation/myReceiptsScreen/MyReceiptsScreenViewModel.kt
> +    /*// Temporary Data
Please remove the commented code.

2024-07-24 01:48 UTC, merged